apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../fiber-example-infra
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: apm-server
  name: apm-server
spec:
  type: NodePort
  ports:
    - name: "8200"
      port: 8200
      targetPort: 8200
      nodePort: 30003
  selector:
    io.kompose.service: apm-server
status:
  loadBalancer: {}
