apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ../fiber-example-infra
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ../fiber-example-infra
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/development: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          image: docker.elastic.co/kibana/kibana:7.8.0
          livenessProbe:
            exec:
              command:
                - curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
            failureThreshold: 20
            periodSeconds: 10
          name: kibana
          ports:
            - containerPort: 5601
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
            limits:
              memory: "550Mi"
              cpu: "150m"
      restartPolicy: Always
status: {}
